version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Entered the install phase...
      - echo Install Maven...
      - yum install -y maven
      - mvn clean install
      - echo Install Maven...
      - echo Entered the install phase...
      - echo "Installing HashiCorp Packer..."
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/0.12.3/packer_0.12.3_linux_amd64.zip && unzip packer.zip
      - echo "Installing jq..."
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      - echo "Validating amazon-linux_packer-template.json"
      - ./packer validate amazon-linux_packer-template.json
  build:
    commands:
      - echo "Configuring AWS credentials"
      - curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - aws configure set region $AWS_REGION
      - aws configure set aws_access_key_id `./jq -r '.AccessKeyId' aws_credentials.json`
      - aws configure set aws_secret_access_key `./jq -r '.SecretAccessKey' aws_credentials.json`
      - aws configure set aws_session_token `./jq -r '.Token' aws_credentials.json`
      - echo "Building HashiCorp Packer template, amazon-linux_packer-template.json"
      - ./packer build amazon-linux_packer-template.json 2>&1 | tee output.txt
      - ami_version=$(tail -2 output.txt | head -2 | awk 'match($0, /ami-.*/) { print substr($0, RSTART, RLENGTH) }')
      - aws ssm put-parameter --name "AMI_VERSION" --type "String" --value $ami_version --overwrite
      - aws ssm delete-parameter --name=AMI_VERSION
      - aws ssm put-parameter --name "AMI_VERSION" --type "String" --value $ami_version
